config/routes.rb
Rails.application.routes.draw do
  get 'analysis/index'
  get 'analysis/show'
  get 'welcome/index'
  get '/welcome/send_mail' , to: "welcome#send_mail"
  devise_for :users
  get '/home',to: "home#index"
  root 'home#index'
  get '/home/download',to: "home#download"
  post '/home/import',to: "home#import"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fileinfo.rb
class Fileinfo < ApplicationRecord
  belongs_to :user
  has_many :records,dependent: :destroy
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :fileinfo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :fileinfos,dependent: :destroy
  has_many :records,through: :fileinfos,dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController

  def index
    @user=user.find(current_user.id)
  end

  def show
    @user_id=current_user.id
    record_repo=RecordRepo.new(@user_id)
    @is_empty=record_repo.get_empty_status
    @max_value=record_repo.get_max
    @median_value=record_repo.get_median
    @count_value=record_repo.get_count
    @domain_hash=record_repo.get_domain_hash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  def download
    send_file(
      "#{Rails.root}/public/sample.csv",
      filename: "sample.csv",
      type: "text/csv",
    )
    # DownloadSample.new.send
  end
  def import
    return redirect_to home_path,notice: "No file added" if params[:file].nil?
    return redirect_to home_path, notice: "only csv file allowed" unless params[:file].content_type=="text/csv"

    file_repo=FileRepo.new(params[:file],current_user.id)
    file_repo.insert

    import_service=ImportService.new
    import_service.call( params[:file], current_user.id,file_repo.file_id)

    path=File.join Rails.root,'public'
    content_type=params[:file].content_type
    original_filename=params[:file].original_filename
    file_path=File.join(path,original_filename)
    # file_path="/opt/code/localstack/localstack/depreciations.py"
    bucket_name="demo"
    object_key="setup"
    # binding.b
    # upload=Upload.new
    # upload.create_bucket(bucket_name)
    # upload.list_buckets
    # upload.put_object(file_path,bucket_name,object_key,content_type)
    # upload.list_objects(bucket_name)

    import_service.upload_file_to_s3(params[:file],bucket_name,file_path,content_type)
    return redirect_to home_path ,notice: "import started "
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
  def send_mail
    WelcomeMailer.send_welcome_mail.deliver_now
  end
end

app/helpers/analysis_helper.rb
module AnalysisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/analysis/index.html.erb
<h1>Analysis#index</h1>
<p>Find me in app/views/analysis/index.html.erb</p>

app/views/analysis/show.html.erb
<h1> Data Analysis</h1>
<% if @is_empty %>
   <h2> Please Insert Data first </h2>
  <%else %>
  <div>
    <p><strong>Max Value:</strong></p>
    <p><%= @max_value %></p>
  </div>
  <div>
    <p><strong>Median Value:</strong></p>
    <p><%= @median_value %></p>
  </div>
  <div>
    <p><strong>Count Value:</strong></p>
    <p><%= @count_value %></p>
  </div>
  <div>
    <p><strong>Time Series:</strong></p>
    <%= line_chart @domain_hash, download: true,title: "time series plot",xtitle: "dates",ytitle: "values"%>
  </div>
  <%end %>

<%= link_to "send_email" ,welcome_send_mail_path %>

app/views/home/_import.html.erb
<%= form_with url: home_import_path,method: :post,multipart: true do |form| %>
  <%= form.file_field :file,accept: ".csv" %>
  <%= form.button "Import file" %>
<%end %>

app/views/home/_user.html.erb
<% if user_signed_in? %>
<%= button_to "sign out",destroy_user_session_path,method: :delete %>
<br>
<%= link_to "edit profile",edit_user_registration_path %>
<% else %>
<%= link_to "sign up",new_user_registration_path %>
<br>
<%= link_to "sign in",new_user_session_path %>
<%end %>

app/views/home/download.html.erb
<h1>your file status</h1>

app/views/home/index.html.erb
<div>
  <h1>Home page</h1>
  <br>
  <%= render "/home/user" %>
  <br>

  <br>
  <%= link_to "download file", home_download_path%>
  <br>
  <% if user_signed_in? %>
  <br>
  <%= render "/home/import" %>
  <br>
    <%= link_to "Data Analysis", analysis_show_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<a href="/send_mail">send mail</a>

app/views/welcome/send_mail.html.erb
<p>mail sent</p>